spring.application.name=url-shortener-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=9642f5ffffd204f4311f7969ff593f2bd71fea4472f6f360e95d7b2c197563f4
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG

frontend.url=http://localhost:5173


